### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by charlie-prezzano** [yespark/heroku-imagemagick-buildpack#3]
Hi,

Thanks for the buildpack! 

I'm checking to see what is needed to also support AVIF file formats. As I'm going through to create WEBP files I was looking to create AVIF as well. 

Take care,
Charlie

**Comment by brian-kephart** [comment]
I've been wondering this too. Here's the results of running `identify -list format`...

...on a heroku dyno with this buildpack:
```
   Format  Mode  Description
-------------------------------------------------------------------------------
     AVIF* ---   AV1 Image File Format (1.12.0)
     HEIC* r--   High Efficiency Image Format (1.12.0)
     HEIF* r--   High Efficiency Image Format (1.12.0)
```

...on my Mac:
```
   Format  Module    Mode  Description
-------------------------------------------------------------------------------
     AVIF* HEIC      rw+   AV1 Image File Format (1.12.0)
     HEIC* HEIC      rw+   High Efficiency Image Format (1.12.0)
     HEIF* HEIC      rw+   High Efficiency Image Format (1.12.0)
```

**Comment by navidemad** [comment]
Avif format is now supported in the lib heic which is included on its latest version in the buildpack.
Did you tested it ?

**Comment by brian-kephart** [comment]
I'm excited to try this out! I deployed the newest version, though, and the listed support didn't change. I'm not sure if this is related to the version rollback on #5 or not. I'm on ImageMagick 7.1.0-25.
```
   Format  Mode  Description
-------------------------------------------------------------------------------
     AVIF* ---   AV1 Image File Format (1.12.0)
     HEIC* r--   High Efficiency Image Format (1.12.0)
     HEIF* r--   High Efficiency Image Format (1.12.0)
```

**Comment by navidemad** [comment]
Since version 7.0.25, it supports AVIF compression natively.
But apparently i should have setup libaom to make it work, can you try again with the new pushed version ?

**Comment by charlie-prezzano** [comment]
I'm using the latest buildpack (commit #2553f7ddc039e1b75a95e3112c74aa2237f2779b, v7.1.0-39) and creating AVIF files :)
