### ISSUE TITLE
Error on Heroku deploy

### ISSUE THREAD

**Issue by TrongHoang21** [yespark/heroku-imagemagick-buildpack#4]
I received the error "This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect"

I tried many ways to include imagemagick into my python project and many buildpacks. But it always throws this error when i'm using TextClip MoviePy on deployment.
The only buildpack that works for me is https://github.com/ello/heroku-buildpack-imagemagick. But it has problem with unicode textclip too. So I don't have any idea what's going on.

Can you help me? many thanks!

**Comment by TrongHoang21** [comment]
I have some images which describe the problem here: https://stackoverflow.com/questions/72161646/heroku-imagemagick-not-detected

**Comment by navidemad** [comment]
I do not know how to resolve your issue, mine is inside a heroku CI with a Rails project.
