### ISSUE TITLE
Error with 7.1.0-39

### ISSUE THREAD

**Issue by charlie-prezzano** [yespark/heroku-imagemagick-buildpack#5]
Rebuilt the Heroku app today and came across errors (below) ... setting the Heroku to use 7.1.0-25 buildpack fixes it.

Heroku Buildpack Link: https://github.com/yespark/heroku-imagemagick-buildpack#154c8c240df1d3fefe362221cac3ae4614e93ab0

Errors:
```
MiniMagick::Error: `magick convert /tmp/ActiveStorage-146013-20220621-3-2ytkha.jpg[0] -auto-orient -resize 250x250> /tmp/image_processing20220621-3-8o0w3g.jpg` failed with error:
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/709.
convert: NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/741.
convert: NoImagesDefined `/tmp/image_processing20220621-3-8o0w3g.jpg' @ error/convert.c/ConvertImageCommand/3325.
```

**Comment by richigonzalez** [comment]
we were experiencing the same issue, so we had to force heroku to use the old buildpack.

**Comment by navidemad** [comment]
Thanks for the feedback. I'm looking for a fix in very short delay. I will let you know.

**Comment by navidemad** [comment]
For the sake of your issue, I just built it again with the version 25.
- Can you provide me more details for me to reproduce the issue. I don't want to keep it at version 25 forever.
- Can you try again with the latest master version

**Comment by brian-kephart** [comment]
I deployed yesterday and saw similar errors. Output below:
```
`magick convert /tmp/ActiveStorage-9939-20220623-52-hdsude.png[0] -auto-orient -resize 560x560> /tmp/image_processing20220623-52-rrj9u7.png` failed with error:
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/709.
convert: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/741.
convert: NoImagesDefined `/tmp/image_processing20220623-52-rrj9u7.png' @ error/convert.c/ConvertImageCommand/3325.
```

I'm using ImageMagick through the MiniMagick Ruby gem, so the rest of the trace is through other libraries. It looks like the original poster is doing the same. I also noticed that `identify -list format` produces no output on my Heroku dyno, so that seems to imply that the problem is in the ImageMagick build rather than the gem.

**Comment by charlie-prezzano** [comment]
I'm using the latest buildpack (commit #2553f7ddc039e1b75a95e3112c74aa2237f2779b, v7.1.0-39) and we are good :)
