### ISSUE TITLE
Incompatibility with heroku-22 stack

### ISSUE THREAD

**Issue by brian-kephart** [yespark/heroku-imagemagick-buildpack#6]
After switching stacks, I'm seeing the following error:
```
error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
```

This error happened in normal use, but the easiest reproduction is:
```bash
heroku run bash
identify -list format
```

I realize that this buildpack isn't built on the new stack yet, but I wanted to report the issue since the new stack will be of concern at some point.

**Comment by greenfork** [comment]
Looks like the problem is that heroku-22 ships with libzip v4 whereas the current build requires v5 https://devcenter.heroku.com/articles/stack-packages

**Comment by navidemad** [comment]
I just replace :
FROM heroku/heroku:20-build
to
FROM heroku/heroku:22-build

But it might need some other adjustements, could you try with this one ?
https://github.com/yespark/heroku-imagemagick-buildpack.git#stack-22

**Comment by brian-kephart** [comment]
Sorry I haven't been able to get to this yet. It might be a bit before I can try it out myself.

**Comment by brian-kephart** [comment]
I made a quick test app [here](https://peaceful-reaches-61420.herokuapp.com/) and all seems to be well!

**Comment by greenfork** [comment]
Can confirm that it works.

**Comment by brian-kephart** [comment]
I've been running the heroku-22 branch in production for a week with no errors.
